[ 2025-03-02 10:22:39,836 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:22:39,862 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:22:39,863 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:22:39,877 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:22:39,888 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:22:40,503 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:22:40,506 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:22:40,506 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:22:40,506 ] 64 root - ERROR - \u274c Prediction failed
[ 2025-03-02 10:23:08,341 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:23:08,343 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:23:08,343 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:23:08,352 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:23:08,355 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:23:08,411 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:23:08,411 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:23:08,411 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:23:08,411 ] 64 root - ERROR - \u274c Prediction failed
