[ 2025-03-02 15:49:17,949 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 15:49:18,013 ] 29 root - INFO - \u2705 Data loaded successfully
[ 2025-03-02 15:49:18,013 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 15:49:18,037 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 15:49:18,038 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 15:49:18,053 ] 28 root - INFO - Creating new features...
[ 2025-03-02 15:49:18,060 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 15:49:18,126 ] 31 root - INFO - \u2705 Data transformed successfully
[ 2025-03-02 15:49:18,935 ] 33 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 15:49:18,936 ] 65 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 15:49:18,936 ] 67 root - ERROR - \u274c Prediction failed
[ 2025-03-02 15:55:08,926 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 15:55:08,949 ] 29 root - INFO - \u2705 Data loaded successfully
[ 2025-03-02 15:55:08,949 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 15:55:08,951 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 15:55:08,952 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 15:55:08,967 ] 28 root - INFO - Creating new features...
[ 2025-03-02 15:55:08,974 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 15:55:09,046 ] 31 root - INFO - \u2705 Data transformed successfully
[ 2025-03-02 15:55:09,195 ] 33 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 15:55:09,196 ] 65 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 15:55:09,196 ] 67 root - ERROR - \u274c Prediction failed
[ 2025-03-02 15:59:30,962 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 15:59:30,998 ] 29 root - INFO - \u2705 Data loaded successfully
[ 2025-03-02 15:59:30,998 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 15:59:31,004 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 15:59:31,005 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 15:59:31,014 ] 28 root - INFO - Creating new features...
[ 2025-03-02 15:59:31,018 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 15:59:31,084 ] 31 root - INFO - \u2705 Data transformed successfully
[ 2025-03-02 15:59:31,312 ] 33 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 15:59:31,312 ] 65 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 15:59:31,312 ] 67 root - ERROR - \u274c Prediction failed
[ 2025-03-02 16:03:47,564 ] 27 root - INFO - \U0001f52e Prediction Started
[ 2025-03-02 16:03:47,588 ] 29 root - INFO - \u2705 Data loaded successfully
[ 2025-03-02 16:03:47,589 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 16:03:47,591 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 16:03:47,591 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 16:03:47,599 ] 28 root - INFO - Creating new features...
[ 2025-03-02 16:03:47,604 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 16:03:47,647 ] 31 root - INFO - \u2705 Data transformed successfully
[ 2025-03-02 16:03:47,762 ] 33 root - ERROR - \u274c Failed to load model: No module named '_loss'
[ 2025-03-02 16:03:47,762 ] 65 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [27] error message[No module named '_loss']
[ 2025-03-02 16:03:47,763 ] 67 root - ERROR - \u274c Prediction failed
